### ISSUE TITLE
Bug: Support for Methods with args

### ISSUE THREAD

**Issue by FerdinandSu** [HIT-ReFreSH/PyMobileSuit#3]
Hi, I'm the developer of this Program, but I don't have enough time to make my program perfect. I'll appreciate it if you can help me improve it and become a contributor. Here is an existing issue:

Methods with args cannot be called as expected. This might be caused by the incomplete dependency injection system.
带参数的方法无法被正常的调用。这可能是由不完备的依赖注入系统导致的。

**Comment by FerdinandSukhoi** [comment]
Please don't hesitate to ask me questions; also, leave comments before you start your work to avoid duplicated work.

如果你有任何疑问，欢迎留言询问我；请在开始前在此留言，防止他人进行重复的工作。
